THUC HANH 5

In [3]:
D = np.array([[1,2],[3,4]])
np.copyto(E, D)
print(E)

E = np.array([[1,2],[3,5]])
np.copyto(E, D)
print(E)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [4]:
x = np.array([['a','b'],['c','d']])
y = 'x'
C = np.matrix([[x, y], [1, 2]])
print(C)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 2) + inhomogeneous part.

In [6]:
A = np.matrix([[[1,2],[3,4]],[[5,6],[7,8]]])

print(A)


ValueError: matrix must be 2-dimensional

In [7]:
A = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(A)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
from numpy import matlib
G = matlib.identity(5)
print(G)

H = matlib.randn(3,2)
print(H)

K = matlib.zeros([4,4])
print(K)




[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[-0.3821236  -0.36876713]
 [ 0.88043291  0.24729674]
 [ 1.38918761  1.75914205]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
import numpy as np

c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]

M = np.asmatrix([[1, 0], [0, 1]])

for i in range(len(c)):
    ci = np.asmatrix([[c[i], 1], [1, 0]])
    if i == 0:
        M = ci
    else:
        M = M * ci

print(M)
print(M[0, 0] / M[1, 0])



[[165707065  80143857]
 [ 52746197  25510582]]
3.1415926535897936


In [12]:
import numpy as np

X = np.array([
    [1, 1],
    [1, 2],
    [1, 3],
    [1, 4],
    [1, 5]
])
Y = np.array([1, 2, 4, 4, 6])

XT = X.T

A1 = np.linalg.inv(XT.dot(X))
A2 = XT.dot(Y)

A = A1.dot(A2)
print(A)

Y_pred = X.dot(A)

error = np.sum((Y - Y_pred) ** 2)
print(error)


[-0.2  1.2]
0.8000000000000003


In [13]:
#BAI TAP CHUONG 5
# BAI 1
import numpy as np

X = np.array([
    [1, 0],
    [1, 1],
    [1, 2],
    [1, 3],
    [1, 4]
])
Y = np.array([10, 8, 7, 5, 2])

XT = X.T

A1 = np.linalg.inv(XT.dot(X))
A2 = XT.dot(Y)

A = A1.dot(A2)
print(A)


[10.2 -1.9]
