THUC HANH 6

In [1]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

tich = np.inner(a,b)
print(tich)


32


In [2]:
import numpy as np

a = np.array([1,2,-3])
np.linalg.norm(a) 

a = np.array([1,2,-3])
np.linalg.norm(a, 1)


np.float64(6.0)

In [3]:
import math
import numpy as np

def chuan(v, k):
    tong = 0
    for i in range(len(v)):
        tong += abs(v[i])**k
    ketqua = math.pow(tong, 1.0/k)
    return ketqua

a = np.array([1,2,-3])

print(chuan(a,1))
print(np.linalg.norm(a,1))

print(chuan(a,2))
print(np.linalg.norm(a,2))

print(chuan(a,3))
print(np.linalg.norm(a,3))

print(chuan(a,1000))
print(np.linalg.norm(a,1000))


6.0
6.0
3.7416573867739413
3.7416573867739413
3.3019272488946263
3.3019272488946263
1.0442214818467515
inf


c:\đại số\LAb3\.venv\Lib\site-packages\numpy\linalg\_linalg.py:2835: RuntimeWarning: overflow encountered in power
  absx **= ord


In [4]:
import numpy as np

m = 10
v1 = np.array([5,-4,3])
v2 = np.array([4,3,-2])
v3 = np.array([-4,-3,-1])
v4 = np.array([-9,8,6])
mi = np.array([2,5,2,1])

M = np.array([v1,v2,v3,v4])
MT = M.transpose()
print(MT)

v = (1.0/m) * MT.dot(mi)
print(v)


[[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]
[1.3 0.9 0. ]


In [5]:
import numpy as np

A = np.array([[0.998, 0.136],
              [0.002, 0.864]])

v0 = np.array([0.95, 0.05])

A100 = np.linalg.matrix_power(A, 100)

v100 = A100.dot(v0)
print(v100)


[0.98550723 0.01449277]


In [7]:
import sympy as sym

x, y = sym.symbols('x y')
xy = sym.Matrix([x, y])
A = sym.Matrix([[1, -68],
                [1,  1]])
v = sym.Matrix([0, 1])

nghiem = sym.solve([A * xy - v])
print(sym.pretty(nghiem))



⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


In [8]:
import numpy as np

A = np.array([[1, 6],
              [5, 2]])

u = np.array([6, -5])

print(A.dot(u))
print(-4 * u)


[-24  20]
[-24  20]


In [9]:
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)
A = sympy.Matrix([[2,3],[3,-6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda*I - A), 0)
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu,4) for phantu in nghiem])
print(sympy.pretty(nghiem))


[-7.000, 3.000]
[-7, 3]


In [10]:
import sympy
x, y = sympy.symbols('x y')
A = sympy.Matrix([[2, 3],
                  [3, -6]])
I = sympy.eye(2)
Lambda = 3
H = A - Lambda * I
hpt = H * sympy.Matrix([x, y])
nghiem = sympy.solve([sympy.Eq(hpt[0], 0), sympy.Eq(hpt[1], 0)], (x, y))
print(sympy.pretty(nghiem))


{x: 3⋅y}


In [11]:
import numpy as np
from numpy import linalg as LA

A = np.array([[2, 3],
              [3, -6]])
D = np.array([[-7, 0],
              [0, 3]])
P = np.array([[-1.0/3, 3],
              [1, 1]])

P1 = LA.inv(P)
print(P1)

print(A.dot(P))
print(P.dot(D))

print(P @ (D ** 1000) @ P1)

print(D ** 2)


[[-0.3  0.9]
 [ 0.3  0.1]]
[[ 2.33333333  9.        ]
 [-7.          3.        ]]
[[ 2.33333333  9.        ]
 [-7.          3.        ]]
[[ 5.03503397e+18  3.50482117e+18]
 [ 3.50482117e+18 -4.31115581e+18]]
[[49  0]
 [ 0  9]]


In [12]:
# BAI TAP CHUONG 6
# BAI 1
import numpy as np
import math

a = np.array([1,2,3])

mag_a = np.sqrt(a.dot(a))
print("Cách a:", mag_a)

mag_b = np.sqrt(a @ a)
print("Cách b:", mag_b)

mag_c = np.sqrt(np.inner(a,a))
print("Cách c:", mag_c)

mag = lambda x : math.sqrt(sum(i**2 for i in x))
print("Cách d:", mag(a))


Cách a: 3.7416573867739413
Cách b: 3.7416573867739413
Cách c: 3.7416573867739413
Cách d: 3.7416573867739413


In [13]:
# BAI TAP CHUONG 6
# BAI 2
import numpy as np

def khoang_cach(u, v):
    return np.linalg.norm(u - v)

def goc_giua_2_vector(u, v):
    cos_theta = np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))
    return np.arccos(cos_theta)

def phep_chieu(u, v):
    p = (np.dot(u, v) / np.dot(v, v)) * v
    return p

# Ví dụ thử nghiệm:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

print("Khoảng cách ||u-v|| =", khoang_cach(u, v))
print("Góc (radian) giữa u và v =", goc_giua_2_vector(u, v))
print("Phép chiếu trực giao p của u lên v =", phep_chieu(u, v))


Khoảng cách ||u-v|| = 5.196152422706632
Góc (radian) giữa u và v = 0.2257261285527342
Phép chiếu trực giao p của u lên v = [1.66233766 2.07792208 2.49350649]
