Thi Thử

In [ ]:
#Câu 1 
import numpy as np
import math

# a)
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
cong_AB = A + B
Ketqua = 3 * A - 2 * B
print("a) Tổng A + B:",cong_AB)
print(" Tích số 3A - 2B:", Ketqua)

# b)
tich_vohuong = np.dot(A, B)

dodai_A = np.linalg.norm(A)
dodai_B = np.linalg.norm(B)
cos = tich_vohuong / (dodai_A * dodai_B)
rad = np.arccos(cos)
doi_sang_do = np.degrees(rad)
print("b) Tích vô hướng A.B:",tich_vohuong)
print("   Góc giữa A và B (độ):", round(doi_sang_do, 3))

# c) 
C = np.array([
    [1, 2, -1],
    [0, 3, 4],
    [2, -1, 0]
])

chuyen_vi = C.T
CtC = np.dot(chuyen_vi, C)
print("c) ")
print("Tích ma trận:",CtC)

a) Tổng A + B: [3 3 1 5]
 Tích số 3A - 2B: [  4 -11  13 -10]
b) Tích vô hướng A.B: -8
   Góc giữa A và B (độ): 108.376
c) 
Tích ma trận: [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


In [ ]:
#Câu 2
import numpy as np
M = np.array([
    [1, 2, 3, 0],
    [4, 5, 6, 1],
    [7, 8, 9, 2],
    [0, 1, 1, 0]
])

N = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]
])

# a) 
tich = np.dot(M, N)
print("a) Tích ma trận M x N:")
print(tich)

# b)
det_M = np.linalg.det(M)
print("b) Định thức của M:",round(det_M, 3))
# Giải thích
if round(det_M, 3) == 0:
    print("Ma trận M không khả nghịch vì định thức = 0.")

# c) Tính hạng của ma trận N
hang_N = np.linalg.matrix_rank(N)
print("c) Hạng của N =", hang_N)


a) Tích ma trận M x N:
[[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]
b) Định thức của M: 0.0
Ma trận M không khả nghịch vì định thức = 0.
c) Hạng của N = 2


In [19]:
#Câu 3
import numpy as np
P = np.array([
    [2, 1, 0, 1],
    [0, 3, 1, -1],
    [1, 0, 4, 2],
    [0, 1, 0, 3]
])

b = np.array([4, 7, 9, 5])

# a)
try:
    ngich_dao_P = np.linalg.inv(P)
    print("a) Ma trận nghịch đảo của P là:\n", np.round(ngich_dao_P, 3))
except np.linalg.LinAlgError:
    print("Ma trận P không khả nghịch (định thức = 0)")

# b) 
try:
    x = np.dot(ngich_dao_P, b)
    print("b) Nghiệm của hệ phương trình là:\n", np.round(x, 3))
except:
    print("Không thể giải vì P không khả nghịch.")

# c) 
try:
    ktra = np.dot(P, x)
    print("c) Kiểm tra P·x = b:\nP·x =", np.round(ktra, 3))
    print("b     =", b)
    print("Đúng" if np.allclose(ktra, b) else "Sai")
except:
    print("Không thể kiểm tra vì không có nghiệm.")


a) Ma trận nghịch đảo của P là:
 [[ 0.488 -0.093  0.023 -0.209]
 [ 0.035  0.279 -0.07   0.128]
 [-0.116  0.07   0.233 -0.093]
 [-0.012 -0.093  0.023  0.291]]
b) Nghiệm của hệ phương trình là:
 [0.465 2.105 1.651 0.965]
c) Kiểm tra P·x = b:
P·x = [4. 7. 9. 5.]
b     = [4 7 9 5]
Đúng


In [25]:
#Câu 4
import numpy as np
Q = np.array([
    [4, -1, 0],
    [1,  3, -2],
    [0,  1,  2]
])

# a)
giatri_rieng, vertor_rieng = np.linalg.eig(Q)
print("a) Các giá trị riêng của Q là:")
print(giatri_rieng)

# b) 
print("b) Các vector riêng tương ứng là:")
print(vertor_rieng)

# c) 
chuan_hoa = giatri_rieng / np.linalg.norm(vertor_rieng, axis=0)
chuan_hoa = np.round(chuan_hoa, 3)

print("c) Các vector riêng đã chuẩn hoá (độ dài = 1):")
print(chuan_hoa)


a) Các giá trị riêng của Q là:
[3.45339765+0.j         2.77330117+1.46771151j 2.77330117-1.46771151j]
b) Các vector riêng tương ứng là:
[[ 0.83327121+0.j         -0.26206044-0.31354813j -0.26206044+0.31354813j]
 [ 0.455468  +0.j         -0.78166743+0.j         -0.78166743-0.j        ]
 [ 0.31338154+0.j         -0.21963176+0.41685708j -0.21963176-0.41685708j]]
c) Các vector riêng đã chuẩn hoá (độ dài = 1):
[3.453+0.j    2.773+1.468j 2.773-1.468j]


In [30]:
#Câu 5
import numpy as np
R = np.array([
    [1, -2, 3],
    [2, 0, 1],
    [-1, 1, 4]
])
b = np.array([10, 8, 7])

# a)
x = np.linalg.solve(R, b)
x = np.round(x, 3)
print("a) Nghiệm của hệ Rx = b là:")
print(x)

# b)
det_R = np.linalg.det(R)
print("b) Định thức của R =", round(det_R, 3))
if det_R != 0:
    R_inv = np.linalg.inv(R)
    ktra_x = np.dot(R_inv, b)
    ktra_x = np.round(ktra_x, 3)
    
    print("Ma trận R khả nghịch. Ma trận nghịch đảo R^(-1) là:")
    print(np.round(R_inv, 3))
    print("Nghiệm khi dùng nghịch đảo R^(-1) · b là:", ktra_x)
    
    print("Hai nghiệm giống nhau:", np.allclose(x, ktra_x))
else:
    print("Ma trận R không khả nghịch.")

# c) 
frobenius = np.linalg.norm(R, 'fro')
frobenius = round(frobenius, 3)
print("c) Chuẩn Frobenius của ma trận R là:", frobenius)


a) Nghiệm của hệ Rx = b là:
[2.783 0.043 2.435]
b) Định thức của R = 23.0
Ma trận R khả nghịch. Ma trận nghịch đảo R^(-1) là:
[[-0.043  0.478 -0.087]
 [-0.391  0.304  0.217]
 [ 0.087  0.043  0.174]]
Nghiệm khi dùng nghịch đảo R^(-1) · b là: [2.783 0.043 2.435]
Hai nghiệm giống nhau: True
c) Chuẩn Frobenius của ma trận R là: 6.083
