In [ ]:
THI THỰC HÀNH 

In [7]:
#BÀI 1
import numpy as np 
import math 

# Câu a
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])

tong_AB = A + B
tich_so_AB = 2 * A + 3 * B
print("a)")
print("Tổng A + B là : ", tong_AB)
print("Tích số 2A + 3B là: ", tich_so_AB)

# Câu b
tichvohuong = np.dot(A, B)
dodai_A = np.linalg.norm(A)
dodai_B = np.linalg.norm(B)
cos = tichvohuong / (dodai_A * dodai_B)
rad = np.arccos(cos)
doi_sang_do = np.degrees(rad)
print("b)")
print("Tích vô hướng cỉa A.B là: ", tichvohuong)
print("Góc giưac hai vector là: ", round(doi_sang_do, 3))

# Câu c

C = np.array([[2, -1, 3],
              [1, 4, -2], 
              [0, 2, 5]])
chuyen_vi =C @ C.T
print("c)")
print("Tích ma trận CCT là: ")
print(chuyen_vi)



a)
Tổng A + B là :  [2 3 1 6]
Tích số 2A + 3B là:  [ 3 11  2 14]
b)
Tích vô hướng cỉa A.B là:  -5
Góc giưac hai vector là:  99.594
c)
Tích ma trận CCT là: 
[[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


In [13]:
# BÀI 2

import numpy as np

# Câu a
M = np.array([
    [2, -1, 3, 0],
    [1, 4, -2, 5],
    [0, 2, 6, -3],
    [-1, 0, 1, 4]])

N = np.array([
    [1, 3, -2, 0],
    [4, -1, 5, 2],
    [0, 2, 3, -1],
    [-3, 1, 0, 4]])

tich_MxN = M @ N
print("a)")
print("Tích của ma trận M x N là: ")
print(tich_MxN)

# Câu b
det_M = np.linalg.det(M)
print("b)")
print("Định thức của ma trận M là: ", round(det_M, 3))

if round(det_M, 3) == 0:
    print("Ma Trận không khả nghịch vì định thức = 0 ")
    
# Câu c 
hang_N = np.linalg.matrix_rank(N)
print("c)")
print("Hạng của ma trận N là: ", hang_N)



a)
Tích của ma trận M x N là: 
[[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]
b)
Định thức của ma trận M là:  409.0
c)
Hạng của ma trận N là:  4


In [18]:
# BÀI 3

import numpy as np
# Câu a
P = np.array([
    [3, -1, 0, 2],
    [1, 4, -2, 0],
    [0, 1, 5, -1],
    [2, 0, 1, 3]])

b = np.array([6, 8, 3, 7])
try:
    nghich_dao_p = np.linalg.inv(P)
    print("a)")
    print("Ma trận nghịch đảo của P:")
    print(np.round(nghich_dao_p, 3))
except np.linalg.LinAlgError:
    print("Ma trận P không khả nghịch (định thức = 0).")
    nghich_dao_p = None

# Câu b
try:
    x = np.dot(nghich_dao_p, 3)
    print("b)")
    print("Nghiệm của phương trình là: ")
    print(np.round(x, 3))
except:
    print("Phương trình không thể giải vì không có khả nghịch")
    
# Câu c 
if nghich_dao_p is not None:
    ktra = P @ x
    print("c)")
    print("Kiểm tra: P @ x ")
    print(np.round(ktra, 3))
    print("So với vector b =", b)


a)
Ma trận nghịch đảo của P:
[[ 0.5    0.1    0.1   -0.3  ]
 [-0.143  0.2    0.057  0.114]
 [-0.036 -0.05   0.164  0.079]
 [-0.321 -0.05  -0.121  0.507]]
b)
Nghiệm của phương trình là: 
[[ 1.5    0.3    0.3   -0.9  ]
 [-0.429  0.6    0.171  0.343]
 [-0.107 -0.15   0.493  0.236]
 [-0.964 -0.15  -0.364  1.521]]
c)
Kiểm tra: P @ x 
[[ 3.  0. -0.  0.]
 [ 0.  3.  0.  0.]
 [ 0.  0.  3.  0.]
 [ 0.  0.  0.  3.]]
So với vector b = [6 8 3 7]


In [19]:
# BÀI 4
import numpy as np
Q = np.array([
    [5, -2, 1],
    [0, 3, -1],
    [2, 0, 4]])

# Câu a
giatri_rieng, vector_rieng = np.linalg.eig(Q)
print("a)")
print("Các giá trị riêng:")
print(np.round(giatri_rieng, 3))

# Câu b
print("b)")
print("Các vector riêng (theo cột):")
print(np.round(vector_rieng, 3))

# Câu c
normalized_vectors = giatri_rieng / np.linalg.norm(vector_rieng, axis=0)
print("c)")
print("Các vector riêng đã chuẩn hóa:")
print(np.round(normalized_vectors, 3))


a)
Các giá trị riêng:
[6.355+0.j    2.822+1.077j 2.822-1.077j]
b)
Các vector riêng (theo cột):
[[ 0.748+0.j    -0.374+0.342j -0.374-0.342j]
 [-0.189+0.j     0.095+0.574j  0.095-0.574j]
 [ 0.636+0.j     0.636+0.j     0.636-0.j   ]]

c) Các vector riêng đã chuẩn hóa:
[6.355+0.j    2.822+1.077j 2.822-1.077j]


In [22]:
# BÀI 5

import numpy as np

R = ([
    [4, -1, 2],
    [1, 3, -2],
    [0, 2, 5]])

b = np.array([12, 5, 9])
# Câu a
x = np.linalg.solve(R, b)
print("a)")
print("Nghiệm x bằng np.linalg.solve():")
print(np.round(x, 3))

# Câu b
try:
    nghich_dao_R = np.linalg.inv(R)
    print("b)")
    print("Ma trận R khả nghịch. Ma trận nghịch đảo R^(-1):")
    print(np.round(nghich_dao_R, 3))
    nghich_dao_x = nghich_dao_R @ b
    print("Nghiệm x tính bằng R^(-1) @ b:")
    print(np.round(nghich_dao_x, 3))

# So sánh nghiệm
    print("\nSo sánh 2 nghiệm:")
    print("Có bằng nhau không? ->", np.allclose(x, nghich_dao_x))

except np.linalg.LinAlgError:
    print("b) Ma trận R không khả nghịch.")

# Câu c
tinh_chuan = np.linalg.norm(R, ord='fro')
print("c)")
print("Tính chuẩn Frobenius của ma trận R:")
print(round(tinh_chuan, 3))

a)
Nghiệm x bằng np.linalg.solve():
[2.788 1.529 1.188]
b)
Ma trận R khả nghịch. Ma trận nghịch đảo R^(-1):
[[ 0.224  0.106 -0.047]
 [-0.059  0.235  0.118]
 [ 0.024 -0.094  0.153]]
Nghiệm x tính bằng R^(-1) @ b:
[2.788 1.529 1.188]

So sánh 2 nghiệm:
Có bằng nhau không? -> True
c)
Tính chuẩn Frobenius của ma trận R:
8.0
