THUC HANH 7

In [1]:
import numpy as np
signals = np.array([[1,2],[3,4],[10,0]])
sample = np.array([3,-1])
np.inner(signals, sample) 

array([ 1,  5, 30])

In [3]:
import numpy as np
A = np.array([0,0,-1,2,3,-1,0,1,-1,-1])
search_vector = np.array([0,1,-1])
len(A), len(search_vector) 
print(len(A), len(search_vector)) 

B = np.array([1])
B = np.resize(B, (len(A)-len(search_vector)+1, len(search_vector)))
B = np.asmatrix(B)
for i in range(len(A)-len(search_vector)+1):
    for j in range(len(search_vector)):
        B[i,j] = A[i+j]
print(B)

C = np.inner(B, search_vector)
for i in range(len(A)-len(search_vector)+1): 
    if ( C[0,i] == np.inner(search_vector, search_vector) ):
        print (i, B[i])


10 3
[[ 0  0 -1]
 [ 0 -1  2]
 [-1  2  3]
 [ 2  3 -1]
 [ 3 -1  0]
 [-1  0  1]
 [ 0  1 -1]
 [ 1 -1 -1]]
6 [[ 0  1 -1]]


In [17]:
from PIL import Image

img = Image.open('Screenshot 2025-07-03 133935.png')
img.height
img.width
img.mode
img = img.convert("RGB")
new_width = int(img.width / 2)
new_height = int(img.height / 2)
new_img = img.resize((new_width, new_height), Image.LANCZOS) 
new_img.save('Screenshot 2025-07-03 133935.png')

In [23]:
from PIL import Image, ImageDraw
input_image = Image.open('Screenshot 2025-07-03 133935.png')
input_pixels = input_image.load()
box_kernel = [[1 / 9, 1 / 9, 1 / 9],
              [1 / 9, 1 / 9, 1 / 9],
              [1 / 9, 1 / 9, 1 / 9]]

kernel = box_kernel
offset = len(kernel) // 2

output_image = Image.new("RGB", input_image.size)
draw = ImageDraw.Draw(output_image)

for x in range(offset, input_image.width - offset):
    for y in range(offset, input_image.height - offset):
        acc = [0, 0, 0]
        for a in range(len(kernel)):
            for b in range(len(kernel)):
                xn = x + a - offset
                yn = y + b - offset
                pixel = input_pixels[xn, yn]
                acc[0] += pixel[0] * kernel[a][b]
                acc[1] += pixel[1] * kernel[a][b]
                acc[2] += pixel[2] * kernel[a][b]
        draw.point((x, y), (int(acc[0]), int(acc[1]), int(acc[2])))

output_image.save('traidat_lammo.PNG')


In [24]:
import numpy as np
from PIL import Image, ImageDraw

# Phần code cho bài 1: Làm mờ ảnh bằng Gaussian Filter
input_image = Image.open('Screenshot 2025-07-03 133935.png')
input_pixels = input_image.load()

gaussian_kernel = [
    [1 / 256, 4 / 256, 6 / 256, 4 / 256, 1 / 256],
    [4 / 256, 16 / 256, 24 / 256, 16 / 256, 4 / 256],
    [6 / 256, 24 / 256, 36 / 256, 24 / 256, 6 / 256],
    [4 / 256, 16 / 256, 24 / 256, 16 / 256, 4 / 256],
    [1 / 256, 4 / 256, 6 / 256, 4 / 256, 1 / 256]
]

kernel = gaussian_kernel
offset = len(kernel) // 2

output_image = Image.new("RGB", input_image.size)
draw = ImageDraw.Draw(output_image)

for x in range(offset, input_image.width - offset):
    for y in range(offset, input_image.height - offset):
        acc = [0, 0, 0]
        for a in range(len(kernel)):
            for b in range(len(kernel[0])):
                xn = x + a - offset
                yn = y + b - offset
                pixel = input_pixels[xn, yn]
                acc[0] += pixel[0] * kernel[a][b]
                acc[1] += pixel[1] * kernel[a][b]
                acc[2] += pixel[2] * kernel[a][b]
        
        r = int(max(0, min(255, acc[0])))
        g = int(max(0, min(255, acc[1])))
        b = int(max(0, min(255, acc[2])))
        
        draw.point((x, y), (r, g, b))

output_image.save('gaussian_blurred_image.PNG')

print("Ảnh đã được làm mờ bằng Gaussian Filter và lưu tại 'gaussian_blurred_image.PNG'")

# Phần code cho bài 2: Tính toán PageRank
# Giả định ma trận A là 4x4 để khớp với việc có x_D trong bảng và phép nhân Ax hợp lệ.
# Cột thứ 4 được thêm vào với giả định để đảm bảo kích thước phù hợp.
A = np.array([[0.0, 0.5, 0.5, 0.0],
              [1.0/3, 0.0, 0.5, 0.0],
              [1.0/3, 1.0, 0.0, 0.0],
              [1.0/3, 0.0, 0.0, 1.0]])

x = np.array([[1.0],
              [1.0],
              [1.0],
              [1.0]])

print("\n--- Tính toán PageRank ---")
print("Lần lặp 0:")
print(f"xA: {x[0,0]:.6f}")
print(f"xB: {x[1,0]:.6f}")
print(f"xC: {x[2,0]:.6f}")
print(f"xD: {x[3,0]:.6f}")
print("-" * 30)

for i in range(1, 11):
    x_new = np.dot(A, x)
    x = x_new
    print(f"Lần lặp {i}:")
    print(f"xA: {x[0,0]:.6f}")
    print(f"xB: {x[1,0]:.6f}")
    print(f"xC: {x[2,0]:.6f}")
    print(f"xD: {x[3,0]:.6f}")
    print("-" * 30)

Ảnh đã được làm mờ bằng Gaussian Filter và lưu tại 'gaussian_blurred_image.PNG'

--- Tính toán PageRank ---
Lần lặp 0:
xA: 1.000000
xB: 1.000000
xC: 1.000000
xD: 1.000000
------------------------------
Lần lặp 1:
xA: 1.000000
xB: 0.833333
xC: 1.333333
xD: 1.333333
------------------------------
Lần lặp 2:
xA: 1.083333
xB: 1.000000
xC: 1.166667
xD: 1.666667
------------------------------
Lần lặp 3:
xA: 1.083333
xB: 0.944444
xC: 1.361111
xD: 2.027778
------------------------------
Lần lặp 4:
xA: 1.152778
xB: 1.041667
xC: 1.305556
xD: 2.388889
------------------------------
Lần lặp 5:
xA: 1.173611
xB: 1.037037
xC: 1.425926
xD: 2.773148
------------------------------
Lần lặp 6:
xA: 1.231481
xB: 1.104167
xC: 1.428241
xD: 3.164352
------------------------------
Lần lặp 7:
xA: 1.266204
xB: 1.124614
xC: 1.514660
xD: 3.574846
------------------------------
Lần lặp 8:
xA: 1.319637
xB: 1.179398
xC: 1.546682
xD: 3.996914
------------------------------
Lần lặp 9:
xA: 1.363040
xB: 1.213220
xC: 1.619